# Generated by Django 5.1 on 2024-10-11 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=150, verbose_name='Nombre del vendedor')),
                ('fecha', models.DateField(verbose_name='Fecha de la compra')),
                ('gastos', models.PositiveIntegerField(verbose_name='Gastos adicionales (Flete, pesada, etc)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones (opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacunador', models.CharField(max_length=150)),
                ('cc_vacunador', models.PositiveBigIntegerField()),
                ('tel_vacunador', models.PositiveBigIntegerField()),
                ('fecha', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=150, verbose_name='Nombre del comprador')),
                ('fecha', models.DateField(verbose_name='Fecha de la venta')),
                ('gastos', models.PositiveIntegerField(verbose_name='Gastos adicionales (Flete, pesada, etc)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones (opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Bovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.BooleanField(choices=[(True, 'Macho'), (False, 'Hembra')], verbose_name='Sexo')),
                ('madre', models.CharField(blank=True, max_length=150, verbose_name='Nombre de la madre (opcional)')),
                ('padre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del padre (opcional)')),
                ('precio_compra', models.PositiveIntegerField(default=0, verbose_name='Precio de compra')),
                ('precio_venta', models.PositiveIntegerField(default=0, verbose_name='Precio de venta')),
                ('peso_compra', models.SmallIntegerField(default=0, verbose_name='Peso al comprar (kg)')),
                ('peso_venta', models.SmallIntegerField(default=0, verbose_name='Peso al vender (kg)')),
                ('topizado', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='¿Está topizado?')),
                ('capado', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='¿Está capado?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones (opcional)')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ganaderia.compra')),
            ],
            options={
                'ordering': ['fecha_nacimiento'],
            },
        ),
        migrations.CreateModel(
            name='VacunaBovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('bovino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.bovino')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.vacuna')),
            ],
        ),
        migrations.AddField(
            model_name='bovino',
            name='vacunas',
            field=models.ManyToManyField(blank=True, through='ganaderia.VacunaBovino', to='ganaderia.vacuna'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ganaderia.venta'),
        ),
    ]
